### ISSUE TITLE
Shopware 5.6.6 Fehler

### ISSUE THREAD

**Issue by artdevil-de** [FriendsOfShopware/FroshFasterCacheManager#2]
nicht kompatibel zu Shopware 5.6.6, triggert 500er Fehler 

[03-Mar-2020 16:25:58 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Shopware\Components\CacheManager::__construct() must be an instance of Zend_Cache_Core, instance of ShopwareProduction3b16a13e350eeedff792d1563cfd55294a454688ProjectContainer given, called in /shopware/httpdocs/custom/plugins/FroshFasterCacheManager/Bundle/CacheManager.php on line 16 and defined in /shopware/httpdocs/engine/Shopware/Components/CacheManager.php:119
Stack trace:
#0 /shopware/httpdocs/custom/plugins/FroshFasterCacheManager/Bundle/CacheManager.php(16): Shopware\Components\CacheManager->__construct(Object(ShopwareProduction3b16a13e350eeedff792d1563cfd55294a454688ProjectContainer))
#1 /shopware/httpdocs/var/cache/production_202003031106/proxies/ShopwareProduction3b16a13e350eeedff792d1563cfd55294a454688ProjectContainer.php(3329): FroshFasterCacheManager\Bundle\CacheManager->__construct(Object(ShopwareProduction3b16a13e350eeedff792d1563cfd55294a454688ProjectContainer))
#2 / in /shopware/httpdocs/engine/Shopware/Components/CacheManager.php on line 119

**Comment by tinect** [comment]
Hey, artdevil-de,

wir prüfen das. Vielen Dank!

**Comment by tinect** [comment]
In Kürze sollte eine neue Version im Store veröffentlicht werden.
Ansonsten kannst du dir in github das Release schon schnappen: https://github.com/FriendsOfShopware/FroshFasterCacheManager/releases/tag/1.0.5

**Comment by artdevil-de** [comment]
Kurz als Bestätigung, Version 1.0.5 erfolgreich in Shopware 5.6.6 getestet.
